name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install npm 
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: get npm version
        run: npm version

      - name: run bash script with env
        shell: bash
        run: |
          chmod +x .github/script/hello.sh
          ./.github/script/hello.sh ${user}      
        env:
          user: kelvin.duan
